# Generated by Django 4.0.5 on 2022-10-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_categories_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default='default_no_image.png', upload_to='category_images'),
        ),
    ]
