# Generated by Django 4.0.5 on 2022-10-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_categories_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(default='Not specified.', max_length=3),
        ),
    ]
